# Generated by Django 3.1.2 on 2020-10-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomber_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parents',
        ),
        migrations.AddField(
            model_name='parent',
            name='child',
            field=models.ManyToManyField(to='bomber_api.Student'),
        ),
    ]
