# Generated by Django 3.1.2 on 2020-10-03 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bomber_api', '0003_auto_20201002_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='child',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='bomber_api.student'),
        ),
    ]
